### ISSUE TITLE
Invalid debutdate being added to character table

### ISSUE THREAD

**Issue by cameronwhite4121** [cameronwhite4121/CPW211-CharacterIndexApp#22]
DebutDate is storing the wrong date into character object, and thus the database. Only want date to be stored, and not datetime.

`// Validate debut date
try
{
    DateTime.TryParse(txtDebutDate.Text.Trim(), out characterDebutDate);
}
catch (FormatException exc)
{
    MessageBox.Show("Debut date must be a valid date");
    validData = false;
}`

**Comment by Azael-Hue** [comment]
I refactored the debutdate in the AddCharacter file on a separate branch, it should add the correct date in any style the user inputs be it (mm/dd/yyyy) (mm dd yyyy) or (mm-dd-yyyy) but time will be added as well to the database as 12:00:00, we could just use DateTime.debutDate.Date when displaying the date to the user.

There is also the issue I encountered that the user might enter an invalid date like 2/30/2003, it will be added to the database regardless as 1/1/0001 alongside the time, i'll check that through

`            // Validate debut date
            try
            {
                DateTime.TryParse(txtDebutDate.Text.Trim(), out DateTime DebutDate);
                characterDebutDate = DebutDate.Date;
            }
            catch (FormatException exc)
            {
                MessageBox.Show("Debut date must be a valid date");
                validData = false;
            }`
