### ISSUE TITLE
Storing duplicate characters

### ISSUE THREAD

**Issue by cameronwhite4121** [cameronwhite4121/CPW211-CharacterIndexApp#23]
It's easy to see a future problem of storing duplicate characters. Before adding a characters to the db, check to see if they're already in there or not

**Comment by Azael-Hue** [comment]
Had initially used an if statement to check through each name to see if there were any matches with the following code:

`            // if the Character is already in the database, show an error message
            CharacterContext dbContextCharacter = new();
            if (dbContextCharacter.Characters.Any(c => c.Name == characterName))
            {
                MessageBox.Show("Character already exists");
                validData = false;
            }`
            
but after the class today, we could probably implement the method Mr Ortiz taught us
